name: db_api
description: The interface and models for an API providing access to database.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.15.0
  uuid: ^4.4.2
  equatable: ^2.0.5

